name: CI / Testar e Empacotar
on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Como incrementar versão?"
        required: true
        type: choice
        options:
          -
          - patch
          - minor
jobs:
#  run_tests:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#        with:
#          fetch-depth: 1
#      # Dispara testes no backend
#      - name: Run tests backend
#        shell: bash
#        working-directory: ./backend/bin/
#        run: ./local-run-test.sh --nowatch
#      # Dispara testes no frontend_web
#      - name: Run tests frontend_web
#        shell: bash
#        working-directory: ./frontend_web/bin/
#        run: ./local-run-test.sh --nowatch

  upgrade_version:
    runs-on: ubuntu-latest
#    needs: [run_tests]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      #Altera versão backend
      - name: "Add version backend"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: "backend"
        with:
          version-type: ${{ github.event.inputs.version_type }}
          skip-tag: "true"
      #Altera versão frontend
      - name: "Add version frontend_web"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: "frontend_web"
        with:
          version-type: ${{ github.event.inputs.version_type }}
          skip-tag: "true"
      #Altera versão docs
      - name: "Add version docs"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: "docs"
        with:
          version-type: ${{ github.event.inputs.version_type }}
          skip-tag: "true"
      #Aguarda uns segundos
      - name: Aguardar 3 segundos
        run: sleep 3s
        shell: bash
      #Compartilha a versão com a pipe
      - name: Save TAG Parameter
        shell: bash
        id: tag_name
        run: echo "::set-output name=TAG::$(cat backend/package.json | jq -r .version)"
      - name: Imprime a tag
        run: echo ${{ steps.tag_name.outputs.TAG }}
    outputs:
      tag: ${{ steps.tag_name.outputs.TAG }}

  run_build_release:
    runs-on: ubuntu-latest
    needs: [upgrade_version]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      # Trocar versão node
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 14.17
      # Builda Docs
      - name: Build Docs
        shell: bash
        run: ./bin/local-build-docs.sh
      # Compacta Docs
      - name: Compact Build Docs
        shell: bash
        run: zip -r docs docs/public docs/package.json
      # Gera o release
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ needs.upgrade_version.outputs.tag }}"
          files: docs.zip
