name: Deploy / Atualizar Servidores

on:
  workflow_dispatch:
    inputs:
      releasetag:
        description: "Nome do artefato/versão"
        type: string
        required: true
      update:
        description: "O que Atualizar?"
        required: true
        default: "todos"
        type: choice
        options:
          - todos
          - servidor
          - frontend_web
          - docs

jobs:
  app_publish_server:
    runs-on: ubuntu-latest

    steps:
      # Baixa a release informada
      - name: Download Release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'thalamusfiles/iam'
          version: "tags/${{ github.event.inputs.releasetag }}"
          file: 'docs.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
      # Descompacta
      - name: Descompact Build
        shell: bash
        run: unzip build.zip 
      # SSH Key
      - name: Baixa KeyPair
        run: |
          echo "${{ secrets.KEYPAIR_PEM }}" > keypair.pem
          sudo chmod 400 keypair.pem
      - name: Adiciona ao known_hosts
        shell: bash
        run: |
          mkdir -p ~/.ssh/
          ssh-keyscan -H ${{ matrix.instanceip }} >> ~/.ssh/known_hosts
          sudo chmod 600 ~/.ssh/known_hosts
      #Atualiza servidor
      - name: Atualiza servidor
        run: rsync -e "ssh -i keypair.pem" -av docs/* ${{ secrets.HOST_CONNECTION }}:${{ secrets.HOST_FOLDER }}
